"""followers

Revision ID: 020a8999a480
Revises: 8635b1cb90a4
Create Date: 2020-06-16 14:44:00.493105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020a8999a480'
down_revision = '8635b1cb90a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
